language: ruby

rvm:
  - 2.2.2
addons:
  apt:
    packages:
    - graphviz
branches:
  only:
  - master
script:
- bundle exec middleman build
deploy:
  provider: s3
  access_key_id: AKIAI3D5RFEP6ABE6NTQ
  local_dir: build
  secret_access_key:
    secure: awcJVnJRmTCDSy7WIptMp1v214wGF8oZXkeuxhM99piqJxMRQ7xcFQNW1M8F8Cf2BPxZkHaTsKM0MyHoDiJbRqVjVvfQ5pN2kOlJELKNs66vMKRojL8RWJIzvzz1iIzc629u70lL9PAkHOG1kKBWYI8VRMTTU6fcwqRTiw7RnEqyil18FtkBRMhrROuGGiVpi0q7VCym+Zl2mfxJYHUKnlERYDCflZelyj6Bnd9BuZfvMezEkogGqUzgVm0zeLLAN8AdGa5vUf+xJKUM9cdqs93IugpUMvbOqHnzXn8HhlSQ/X8IfEsdZRQwAtr5egtil21vjBjsjwr+EnUMumcE9b7xBbIey2HiZ14Yn1RoW9GRSSQe997Qj5nXNCOkxZJT7hFTto5fwrMH0mDP4U0Y0W8V7Nd6564iPDWMX6nEJBvEkUsPElQlUcZuOo14/ivUf4nodRkw0H9ZpYW/iuyXSj4icq2/kK56BkM7IbY3nHloSves1gd4dbA6B80xPF0NCAAe7ALZGmdox3ikjhI2Hmjb+32fwoQtXFVwm9KOLI8irjBKlfajbtXaf3Z3A2vwOXBnmK3Y+ro1OqRX91qJh/yE0APZWPUCXVcq9ERecFXnsLNUWKwFxtnAoWX10pk3MC9z867O7rRngL18fcmGlMFcZ3fbrxDbNgjwo/5P6Lg=
  bucket: l1zard.xn--onks-99b.com
  acl: public_read
  on:
    repo: amonks/lizard

