language: ruby
addons:
  apt:
    packages:
    - graphviz
branches:
  only:
  - master
script:
- bundle exec middleman build
before_deploy:
  - rvm 1.9.3 do gem install aws-sdk -v 2.1.36
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAI3D5RFEP6ABE6NTQ
  secret_access_key:
    secure: gSpuEIw4zyawkN0NncJ+eMaFjIyiSlbsPAROOoGPBFE0yQ6GMngEJJHiMS6Bl9R7FXZZOW5L8xjUOVMUfPjBHyunV3zW8wzQ2lNsZplRkWnAYfqU64Mlm4aG0IXrG21I+2/8u0mqaLp7izZOYFtE/I94OuKg1lENZzLQj7BqDDqLGkezBQVl7Zxciuivtu70ylXTLrc8mF0cx+hlV/DmxepZCbEPmG3lV4H/kku1CzWFflY/XFJeoHe/NIsksoVgcmCGPUdcwsTwL9T9p5Eld0jmbQaDK0ouxziavhry3uC+Sd//PWiLsiDJ9pojq3Ggw/yx8b2CCYnDh9vIdKStJ5p/CL7WibKNN/mGs9cviCy4dR3lhhth7C5Pq0dsRuXi69gePKYrIPUwVSJSgxvkVtROJwVifbcWxsD2spvrZPwRH5jo8GdtNpbpjMzbmlIUMQYi14Eg4sSKENTsjvKtN6Ij0kIJ1QlrE929CSyx1VNo+LJXBXwcrHBywkbeXGmGnbFBmJzIoUcPUpg2AabXjGNgmePcDq4v8dQPZ+V13Z7Tf5vgFfn4CQikKy4tcBY+4puncul93CdMolfbqqN+0pB4bizitTmyZO4Z80NNv+Il8qyLm2u7/ZibVczdHAOI4/L4/5CHKN0Qdfu6Z/yuTyK7tUxpP3Opvflf/T0B79o=
  bucket: l1zard.xn--onks-99b.com
  local_dir: build
  acl: public_read
  on:
    repo: amonks/lizard
