language: ruby
addons:
  apt:
    packages:
    - graphviz
branches:
  only:
  - master
script:
- bundle exec middleman build
before_deploy:
- rvm 1.9.3 do gem install aws-sdk -v 2.1.36
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAI3D5RFEP6ABE6NTQ
  secret_access_key:
    secure: Jxp8oOWBoz9wyqTzeMopgUUAhu2JMsweRAZggRLa9nvd39XqGq1wyPSMEN+jLfiJ9hsLO4uLZWoseGF6xl3teF25uhTWcqQH0zGqs62jliGlxPZbdEo6l8npYFYaTL+ypwQyv7qGdeFvxUyNW5YmGkq+mLSsFVdIEXnmKqMQyhDN2DUoFF7yYTdVRpMSPoOgxZOEab4KyUnloycCMfqVq+STW1iFX/qlwtqvZy8NY9xCvZEVbrA8L1/FXW/2Qkdyn/Q1Xxp4YxHSBjmKgdWLtQ+OXJSLPofUxYKjINum/OrotUdk0O4STXJqB7D4SHxt3wOtd2hiSktGpNcZjArrrbnZyXRtT4FbHKlH0ZCvOLSXO5kn/ZriigbkhV/upwZHhFUNxhqevfsugV0HmdAejrX7dG064I1SJJg1I6kvyXhBRMp8rGMYVSBP4T+E9FLUTaPe9ZobEFMlm6JqIaOowr4GtnVv7TXaexh3OPtjq7d8bYZe79ydgBbI6uHcvJI1J+SXFi3SUmTiQ0yyHF+iCHe/IdI62WQxvvG/gpSfYXu9ILnJR+wYSAdL4bRDS19DwSfGpUoVwTpGvzC1ua8xQbzLZgALo/2zNonMqv+63eDpV/42VfnehTk0xSiAwvDk9RJ567TJi+K18Dnlzv1vgoVgg5b6ozr93KzmoK8GR3E=
  bucket: l1zard.xn--onks-99b.com
  local-dir: build
  acl: public_read
  on:
    repo: amonks/lizard
